### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by rogeramitchell** [requestly/footer#1]
With extension release v4.2.12, Chrome identifies an issue with loading unsafe scripts because of this footer component.

I recommend changing to use https.

**Comment by sachinjain024** [comment]
@rogeramitchell Actually, I was hit by a DNS issue due to which requestly.in went down. Therefore, I had to make requestly rules page up on requestly.github.io but left the footer on requestly.in. Github pages hosting does not allow custom domains to be hosted on https. 

So this issue cannot be addressed until github provides support for https on custom domains.

**Comment by rogeramitchell** [comment]
Got it, thank you for the quick response! Feel free to close this issue if you do not want to keep it open pending Github providing support.

**Comment by sachinjain024** [comment]
I am already tracking this ticket: https://github.com/isaacs/github/issues/156 for supporting https for custom domains.

Thanks for confirmation. I need to close this down. This is already under radar.
